AWS_ACCESS_KEY_ID = "AKIAUE4WBHMYBJJG27E6"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"

[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "stream_users"
username = "postgres"
password = "1234"