AWS_ACCESS_KEY_ID = "X"
AWS_SECRET_ACCESS_KEY = "X"
AWS_DEFAULT_REGION = "us-east-1"

[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "X"
username = "X"
password = "X"
