AWS_ACCESS_KEY_ID = "XXXXXXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY = "XXXXXXXXXXXXXXXX"
AWS_DEFAULT_REGION = "us-east-1"

[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "XXXXXX"
username = "XXXXXX"
password = "XXXXX"

